---
services:
  updater:
    container_name: adblock
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - 'bind9-zones:/bind-adblock'
      # - '/var/bind:/bind-adblock'

volumes:
  bind9-zones:
