#! /usr/bin/env bash

(
cd /opt/bind-adblock;
source ./venv/bin/activate;
python3 ./update-zonefile.py /var/bind/pri/rpz-adblocker.zone rpz.adblocker;
deactivate
) > /var/log/rpz-adblocker.log 2>&1


